apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstageclifourteen
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    # instanceName and github-organization-project-name are optional. The value is a string and should be enclosed in double quotes ""
    jenkins.io/job-full-name: "Mukta-Hexaware/backstageclifourteen"
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
